### ISSUE TITLE
Tagesbeleg (Nullbeleg) mit "Signatureinrichtung ausgefallen"

### ISSUE THREAD

**Issue by arigelni** [BMF-RKSV-Technik/at-registrierkassen-mustercode#400]
Guten Tag, 
ich lasse Tagesbelege erstellen (Tageslosung als Nullbeleg) und hatte den Fall, dass die Signatureinrichtung ausgefallen war. Nun wurde er "korrekt" mit "Signatureinrichtung ausgefallen" markiert jedoch bringt mir das Prüftool folgende Fehler (aus cashbox.json)

{
  "verificationId" : "VERIFICATION_FROM_CASHBOX",
  "version" : 1,
  "verificationName" : "Prüfergebnis - Kasse",
  "verificationTextualDescription" : "Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.",
  "verificationState" : "FAIL",
  "verificationResultDetailedMessage" : "Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Am besten, Sie  übermitteln zur Problembehandlung die nachfolgende Fehlerbeschreibung an Ihren Kassenhersteller.",
  "verificationTimestamp" : "2017-03-09T16:54:36.577+01:00",
  "verificationResultList" : [ {
    "verificationId" : "RECEIPT_FULL",
    "version" : 1,
    "verificationName" : "Detailprüfung des maschinenlesbaren Codes",
    "verificationTextualDescription" : "Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.",
    "verificationState" : "FAIL",
    "verificationTimestamp" : "2017-03-09T16:54:36.579+01:00",
    "verificationResultList" : [ {
      "verificationId" : "STATE_CONSOLIDATED",
      "version" : 1,
      "verificationName" : "Statusprüfung der Kasse und Signatur-/Siegelerstellungseinheit",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die Zustände der Kasse und der verwendeten Signatur-/Siegelerstellungseinheit und die Ergebnisse der zuvor durchgeführten Prüfungen (vor allem der Belegtyp) ausgewertet. Handelt es sich um einen Startbeleg, wird überprüft ob eine Inbetriebnahme der Kasse möglich ist.",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2017-03-09T16:54:36.581+01:00",
      "verificationResultList" : [ {
        "verificationId" : "STATE_SIGDEVICE",
        "version" : 1,
        "verificationName" : "Statusprüfung der Signatur-/Siegelerstellungseinheit",
        "verificationTextualDescription" : "Es wird der Status der Signatur-/Siegelerstellungseinheit zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet.",
        "verificationState" : "FAIL",
        "verificationResultDetailedMessage" : "Dieser Nullbeleg wurde nicht kryptographisch signiert. Ein Nullbeleg muss über eine gültige Signatur verfügen.",
        "verificationTimestamp" : "2017-03-09T16:54:36.581+01:00"
      } ]
    } ]
  } ]
}

Wie soll man damit umgehen? Wenn die Signatureinrichtung ausgefallen ist, sollten auch Nullbelege weiterhin erstellt werden können...
Ich bitte um kurze Hilfestellungen. DANKE

**Comment by ztp-mino** [comment]
aus der readme:
> Im Prüftool mit der Version 1.0.0. wird bei allen Nullbelegen verlangt, dass eine Signatur vorhanden ist (also der Beleg nicht mit “Sicherheitseinrichtung ausgefallen” markiert ist). Diese Funktion wird in der nächsten Version wie folgt geändert: Das Prüfergebnis wird nach wie vor bei allen Nullbelegen ohne Signatur negativ sein, an Stelle der Fehlermeldung wird allerdings ein Hinweis ausgegeben, der auf die oben genannte Kategorisierung verweist. Der Prüfvorgang wird nicht abgebrochen. Da es sich um den selben Prüfkern wie im FinOnline handelt, wird auch dort die gleiche Meldung zu sehen sein.

Wir haben ein eigenes Prüftool geschrieben, das schon jetzt dieses geplante Verhalten implementiert. Ist zu finden unter https://github.com/ztp-at/RKSV

**Comment by arigelni** [comment]
Vielen Dank für die rasche Antwort, habe auch gerade gesehen, dass es da schon ein Ticket gibt. Die Antwort vom BMF ist aber dennoch ausständig...
Ich prüfe mal mit ihrem Tool :-)

**Comment by ztp-mino** [comment]
Ich gebe noch zu bedenken, dass unser Tool nicht in Abstimmung mit dem BMF gemacht wurde und wir nicht für die Korrektheit der Ergebnisse garantieren können.

**Comment by arigelni** [comment]
Verstehe...
wann ist seitens des bmf mit einem neuen Prüftool zu rechnen?
Die jetzige Situation ist nicht sehr befriedigend, wenn die Prüfung abgebrochen wird. In meinem Fall warten da noch etliche Belege auf die Überprüfung.

**Comment by ztp-mino** [comment]
Wurde soweit ich weiß bereits mehrmals gefragt. Das A-SIT Prüftool wird alle einzelnen Belege prüfen, allerdings wird später, in der DEP Überprüfung abgebrochen wenn ein unsignierter Null-Beleg gefunden wird. D.h. was tatsächlich nicht geprüft wird sind Dinge wie die Entwicklung des Umsatzzählers oder die korrekte Verkettund der Belege. Soweit ich weiß ist unser Tool hier bislang die einzige Lösung.

Bis das neue offizielle Prüftool da ist scheint die beste Lösung zu sein, die Einzelbelegprüfung mit dem A-SIT Plus Tool zu erledigen und das DEP nochmals mit unserem inoffiziellen Tool zu testen...

**Comment by arigelni** [comment]
Eine Frage hätte ich noch. Wie erkennt das Prüftool den Unterscheid von einem Nullbeleg zum anderen? Sprich Monatsbeleg oder Prüf-Nullbeleg zb? Denn Jahresbelege (auch Monatsbelege) dürfen nicht  mit "Sig.einrichtung ausgefallen" markiert werden, Monatsbelege schon...

**Comment by ztp-mino** [comment]
Unseres? Garnicht. Es erkennt den Startbeleg und erwartet, dass der signiert ist und es erkennt wenn nach dem Ausfall der Signaturerstellungseinheit ein signierter Nullbeleg erforderlich ist und checkt ob der da ist. Es ist für das RKSV-DEP soweit ich weiß nicht genau spezifiziert wie ein Jahresbeleg zu kennzeichnen ist, daher vermute ich, dass das das beste ist, das man machen kann. Bei Jahresbelegen muss man selber drauf schaun. Daher vermutlich auch das Verhalten in dem versprochenen Prüftool, dass nicht signierte Nullbelege noch immer als Warnungen angezeigt werden.

**Comment by ErichFreitag** [comment]
Im RKSV-DEP gibt es keine Spezifikation für einen Jahresbeleg o.ä. Erkennen kann man das am Datumssprung, ebenso einen Monatsbeleg.

**Comment by arigelni** [comment]
Und wie erfolgt die Unterscheidung zwischen Nullbeleg, der als "Tageslosung" fungiert und einem Sammelbeleg? Beide 0 Euro Umsätze

**Comment by ztp-mino** [comment]
Ist in der RKSV auch nicht weiter spezifiziert.

**Comment by ErichFreitag** [comment]
Bezüglich Arten von Nullbelegen siehe Forum - Startseite.

Eine Tageslosung gibt es in der RKSV überhaupt nicht. Ein Sammelbeleg ist hingegen eindeutig identifizierbar. Er muss er der erste vor oder nach einem wieder signierbaren Beleg eingeschobene Nullbeleg sein. Im beispielsweise Kassenjournal muss zusätzlich Beginn und Ende des SEE-Ausfalls enthalten sein. Der Sammelbeleg ist damit einfach über eine wieder gültige Signatur nach SEE-Ausfall erkennbar.

**Comment by arigelni** [comment]
Den "Tageslosung"-Beleg erstelle ich, um das Ende eines Tages zu kennzeichnen. Nicht zwingend natürlich. Jedoch handelt es sich um einen Null-Beleg. In meinem Fall werden die Sammelbelege auch nach dem ersten signierten Beleg erstellt und somit eindeutig erkannt. Jedoch wurde in diesem speziellen Fall ein Nullbeleg (Tageslosung) mit "ausgefallen" markiert. (Am nächsten Tag war die Signaturkarte wieder korrekt verfügbar und eine Buchung wurde getätigt. Sofort danach auch der Sammelbeleg...)

**Comment by ErichFreitag** [comment]
Das würde ich nicht tun, weil a) einen Kontrollbeleg müssen sie jederzeit erzeugen können und b) einen Monatsbeleg müssen sie ebenso erzeugen können - unabhängig von der Funktion der Signaturerstellungseinheit. Einen Tagesbeleg können sie dennoch ebenso unabhängig von der Signaturerstellungseinheit erzeugen - auch wenn es das Prüftool derzeit noch als fehlerhaft markiert.

**Comment by arigelni** [comment]
Nun gut, ich werde auf das Prüftool warten und gegebenenfalls die Anweisung wieder entfernen. Vielen Dank für die Rückmeldungen !

**Comment by TKast** [comment]
Wie sieht es mit "Signatureinrichtung ausgefallen" bei Jahresbelegen aus?
Muss man die Kasse deaktivieren (Belegerstellung verbieten), bis ein signierter Nullbeleg (Jahresbeleg) erstellt werden kann?

**Comment by arigelni** [comment]
Jahresbelege dürfen nicht mit "Sig ausgefallen" markiert werden. 
Ich lasse keinen Beleg zu, bis Sigeinheit wieder einsatzfähig ist. 

@ErichFreitag Haben Sie schon Informationen erhalten zwecks aktualisiertem Prüftool?

**Comment by ErichFreitag** [comment]
@arigelni - danke der Nachfrage, ich kann das - da ich nicht A-SIT- und auch nicht BMF-Mitarbeiter bin - nicht beantworten.

**Comment by arigelni** [comment]
:-) verzeihung das sollte sich natürlich an @pteufl  richten

**Comment by asitplus-pteufl** [comment]
@arigelni Kann ich leider nicht beantworten, wurde ans BMF weitergeleitet.
