### ISSUE TITLE
Fehler in DEP Export

### ISSUE THREAD

**Issue by TMF42** [BMF-RKSV-Technik/at-registrierkassen-mustercode#622]
Wo kann man Informationen für Kassenhersteller finden wie bei der Korrektur von Fehlern in der Software vorzugehen ist. 

Konkret geht es darum dass der Umsatzzähler bei einer Kassa falsch ist und die Addition zum Vorbeleg falsch durchgeführt wurde. Jetzt haben wir DEP Einträge die von der Verschlüsselung und Verkettung her passen aber der Umsatzzähler nicht korrekt summiert wurde.

**Comment by ErichFreitag** [comment]
Informationen und Aussagen dazu gibt es in den XING- und WKO-Foren zur RKSV.

Ein Fehler im Umsatzzähler ist ein schwerer Mangel -> Kasse außer Betrieb nehmen, dokumentieren und eine neue Kasse in Betrieb nehmen.

**Comment by TMF42** [comment]
Vielen Dank - Ich hab die Foren auch zuvor schon durchforstet aber es sind teilweise widersprüchliche Aussagen zu finden. Manche schreiben dass eine Dokumentation des Fehlers und Behebung genügt - manche sagen, dass man die Kassa neu anmelden sollte. 

Ich verstehe dass die Neuanmeldung die sauberste Variante ist aber ich hätte gerne offiziellere Infos.

**Comment by eczach** [comment]
in der WKO-arbeitskreissitzung vom 18.04.2017 wurde vom BMF wie folgt referiert (war bei dem termin auch selber vor ort und habe explizit zu diesem thema nochmals im gespräch nachgefragt:

Programmierfehler in der RK
* bei  einem Programmierfehler kann nicht von einem vorsätzlichen Begehen
ausgegangen werden (§51 FStG greift nicht)
* Fehler sind immer schnellstmöglich zu beseitigen (Initiative des
Richtigstellens, Dokumentation)
* Programmierfehler, wie falsche Zuordnung der Beträge zu den Steuersätzen
oder Umsatzzähler, die bei gewissen Geschäftsfällen fälschlicherweise nicht
verändert werden, werden als nicht schwerwiegend angesehen, müssen aber
– wie oben ausgeführt - so rasch wie möglich beseitigt werden
* Verkettungsfehler sind gravierende (schwere) Fehler

vgl. protokoll - foliensatz des bmf, seite 13
