### ISSUE TITLE
Bankomatzahlung am ende des Monats

### ISSUE THREAD

**Issue by AlgoLinz** [BMF-RKSV-Technik/at-registrierkassen-mustercode#648]
Hallo,

habe eine eher nicht technische Frage. Vielleicht kann sie jemand beantworten.

Der Kunde erstellt ein Beleg am 30.September der sofort mit Bankomatkarte bezahlt wird. Der Beleg wird mit dem Datum 30.Sep. erstellt.

Das Geld bekommt der Kunde erst am 02.Oktober am Kundenkonto (Bank) von Bankomatbetreiber. Auch auf der Abrechnung des Betreibers steht der Betrag mit dem Datum 02.Okt

Im welchen Monat zählt dieser Umsatz? Ist es September oder Oktober Umsatz?
Laut Registrierkasse ist es September-Umsatz.

Danke im Voraus.

**Comment by ErichFreitag** [comment]
Aus Sicht der Kasse zum Zeitpunkt des Barumsatzes, in diesem Fall eben mit EC-Karte. Der Abgleich zwischen Kasse (offene Forderung vom 30.09.) und Umsatz am Konto (Ausgleich am 02.10.) muss in der Buchhaltung erfolgen, vergleichbar zu einer Rechnungsstellung mit Zahlungsziel.

**Comment by AxelKutschera** [comment]
Immer September 
Bankomat = Debit. Daher hier keine Frage.

**Comment by AlgoLinz** [comment]
Eventuell zu erwähnen, der Kunde fällt nicht unter der doppelten Buchhaltung => er führt eine Eingabe/Ausgabe Rechnung

**Comment by AxelKutschera** [comment]
Das gilt auch bei der EA-Rechnung. 

Meine Antwort war so kurz, da die Berücksichtigung aller Fälle ein paar Seiten füllen würde. 
Zudem gibt es in vielen Fällen die Praktiker-Lösung, welche vielleicht nicht in jedem Detail der gesetzlich vorgegeben ist.  Dann gilt die sinngemäße Auslegung des Gesetzeszwecks.

**Comment by AlgoLinz** [comment]
Danke :)
