### ISSUE TITLE
Journal konnte bei einer Zielrechnung nicht aktualisiert werden

### ISSUE THREAD

**Issue by AlgoLinz** [BMF-RKSV-Technik/at-registrierkassen-mustercode#654]
Hallo,

kann mir vielleicht jemand sagen wie man sich in folgender Situation verhalten soll:

Zusätzlich zu den BAR-Belegen protokolliere ich unter anderem auch die Erstellung und Änderung von den Zielrechnungen im Journal (nicht DEP). DEP ist davon nicht betroffen, die Summenzähler sind davon nicht betroffen und auch die Belegnummerkreis ist davon nicht betroffen.

Es wird eine Zielrechnung aktualisiert und während der Speicherung konnte die Änderung der Zielrechnung im Journal nicht protokolliert werden (dem Kunden wurde eine Fehlermeldung ausgegeben).

Wie ist in so einer Situation vorzugehen?
Einfach mit der Registrierkasse weiter machen (intern, natürlich die Ursache analaysieren und eventuellen Fehler beheben) oder soll auch in dieser Situation die Kasse abgemeldet und eine neue angemeldet werden (weil Journal in diesem Fall nicht mehr alle Änderungen enthält).

Danke im Voraus

**Comment by AxelKutschera** [comment]
Dieser "Fehler" hat nicht direkt mit der RKSV zu tun. Die Verkettung der Belege ist korrekt. 
Das entstandene Datenerfassungsprotokoll (Journal) ist immer zu interpretieren.
Daher ist die nachvollziehbare Dokumentation das einzige, was sinnvoll zu machen ist.
In der EDV dürfen auch Fehler gemacht werden. Wenn das passiert, sollten Maßnahmen ergriffen werden, um diese Fehler möglichst zu vermeiden.

**Comment by AlgoLinz** [comment]
Danke für die Rückmeldung.
