### ISSUE TITLE
Startbeleg Fehler ["TYPE_RECEIPT" : "NULL"]

### ISSUE THREAD

**Issue by RkRKlink** [BMF-RKSV-Technik/at-registrierkassen-mustercode#659]
Hallo Zusammen,

hoffentlich kann mir hier jemand Helfen. Nach einem erneuten Testen meiner Belege mit dem neuen Prüftools schlägt die Prüfung fehl. Es wird kein gültiger Startbeleg am Anfang gefunden. Ich bin alles nochmal durchgegangen und weiß einfach nicht wo der Fehler liegt. 
Hoffentlich kann mir hier jemand Helfen.

Vielen Dank schon mal im voraus!

[DEP-full.txt](https://github.com/BMF-RKSV-Technik/at-registrierkassen-mustercode/files/1815516/DEP-full.txt)
[DEP_0002.txt](https://github.com/BMF-RKSV-Technik/at-registrierkassen-mustercode/files/1815517/DEP_0002.txt)
[cryptographicMaterialContainer.txt](https://github.com/BMF-RKSV-Technik/at-registrierkassen-mustercode/files/1815519/cryptographicMaterialContainer.txt)

**Comment by ErichFreitag** [comment]
Die gute Nachricht: das DEP ist soweit korrekt und OK, zumindest bezüglich dem ersten Beleg.

Die Seltsamkeit: wenn ich ihren Zertifikatsstring bei mir verwende, erhalte ich beim Auslesen statt "40B9650E" die Angabe "â€Ž40B9650E". Ich sehe jedoch die Zeichen am Beginn im Crypto-File nicht, auch nicht mit einem Editor, der Sonderzeichen anzeigt. 

Wenn ich die Seriennummer 40B9650E nochmals händisch neu in den Crypto-File eintrage funktioniert es.

**Comment by RkRKlink** [comment]
Hm okay vielen Dank schon mal. 
Jetzt muss ich nur noch herausfinden warum er da diese Vorzeichen hat.
Sie haben in dem CryptoContainer die Seriennummer händisch noch einmal eingetragen oder wo genau? Damit ich schon mal unterscheiden kann, in welcher Datei ich den Fehler suchen muss.

**Comment by ErichFreitag** [comment]
Im CryptoContainer, genau.

**Comment by RkRKlink** [comment]
Vielen Dank! 
Ich habe die Datei dann mal mit dem TinyHexer geöffnet und das Problem gefunden. Jetzt ist er ohne Probleme durchgelaufen.

**Comment by lebail** [comment]
In Ihrem CryptoContainer befindet sich jeweils am Beginn der Seriennummer das UTF-8-Zeichen mit der 3-Byte-Darstellung E2 80 8E (hex). Dieses ist ein unsichtbares Steuerzeichen namens "left-to-right mark", welches von Textverarbeitungsprogrammen bei der Mischung verschiedener Schreibrichtungen (z.B. beim Einfügen eines arabischen Wortes in einen englischen Satz) benutzt wird.

Dieses sollten Sie herauslöschen …
