### ISSUE TITLE
Hallo zusammen

### ISSUE THREAD

**Issue by gschni** [BMF-RKSV-Technik/at-registrierkassen-mustercode#666]
ich habe ein perfektes dep bis zu dem tag nach einer 4wöchigen gschäftspause !
nach einem duchlauf mittels prüftool 1.1.1 kam die meldung
"Am Beginn des exportierten RKSV-DEP befindet sich kein gültiger Startbeleg."
ab dem 1. eintrag nach dem urlaub
ich dachte man kann betriebsurlaube ignorieren ?
vielen dank im voraus

**Comment by ErichFreitag** [comment]
Das können sie grundsätzlich auch. Darüber hinaus haben Lücken durch Urlaube o.ä. mit dem DEP-Export nichts zu tun - da liegt der Fehler wo anders (falsches Startdatum für Export, ...).

**Comment by AxelKutschera** [comment]
Wenn der Wunsch des Finanzamtes ist, ein DEP7 von zB nur einem Monat (nicht dem ersten Monat mit Startbeleg) zu exportieren, dann kommt diese Fehlermeldung immer.

Der Export ohne Startbeleg - also für ein spätereren Zeitraum - WAR meiner Meinung nach aber nicht der ursprüngliche Gedanke der RKSV.

**Comment by gschni** [comment]
ja das verwundert mich eben. ich habe den zeitraum vom startdatum bis einen tag nach betriebsöffnung eingegeben !

**Comment by ErichFreitag** [comment]
Tja, also Fehler suchen.

Wenn möglich DEP bis vor Urlaub exportieren und prüfen. Wenn OK - soweit gut.

Dann DEP bis nach Urlaub exportieren und prüfen - wieviele Datensätze sind dann enthalten? Was ist der erste Eintrag?

Es kann auch ein Kassenfehler sein (das klingt zumindest so) - also irgendwo ein Zusammenhang mit der Erzeugung von Monatsbelegen, Neustart des DEP-Exports nach der Pause, ...

**Comment by gschni** [comment]
ich habe jetzt die drei test durchgeführt und meiner meinung hat das prüftool einen fehler !
prüfung vom startbeleg bis urlaub alles in ordnung
prüfung vom tag nach urlaub die plausieble meldung
"Am Beginn des exportierten RKSV-DEP befindet sich kein gültiger Startbeleg."

der selbe fehler kommt wenn ich vom startweg inkl. bis nach dem urlaub in einem alles durchlaufen lasse
"Am Beginn des exportierten RKSV-DEP befindet sich kein gültiger Startbeleg."
obwohl siehe erster lauf eingültiger startbeleg vorhanden ist
der betriebsurlaub dauerte auf 4 wochen !

**Comment by ErichFreitag** [comment]
Das Prüftool hat normalerweise keinen Fehler, obwohl ich es nicht ausschliessen kann.

Wenn sie bis zum letzten Tag vor dem Urlaub exportieren - wie viele Datensätze sind dann enthalten?

Wenn sie bis zB einen Tag nach dem Urlaub exportieren - wie viele Datensätze sind dann enthalten?

Was ist der letzte Eintrag vor dem Urlaub und was sind die ersten beiden Einträge nach dem Urlaub?

Es kann auch die Kassensoftware durch die Unterbrechung einen Fehler produzieren.

**Comment by gschni** [comment]
eine kurze frage bitte ! gibt es eine möglichkeit einer abfrage ob die signatureinheit aktiv oder ausgefallen ist ? bei usb sticks ist dies sehr oft der fall ! danke im voraus
