### ISSUE TITLE
Verständnisproblem wegen Verkettung

### ISSUE THREAD

**Issue by j0k3rabg** [BMF-RKSV-Technik/at-registrierkassen-mustercode#673]
Hab erfolgreich geschafft den Startbeleg zu erstellen, bei den ersten echten Beleg kriege ich aber von FON die folgende Fehlermeldung:

> Bei der Überprüfung des maschinenlesbaren Codes wurde ein Fehler beim Abgleich des Signaturwertes mit dem öffentlichen Schlüssel festgestellt. Bitte überprüfen Sie, ob die verwendete Signatur- bzw. Siegelerstellungseinheit korrekt in FinanzOnline registriert wurde.

Womit kann diese Fehlermeldung hängen? Hab diverse Antworten mir angeschaut aber leider hat keiner geholfen.

**Comment by ErichFreitag** [comment]
Wo haben sie genau was geprüft? FON-Anbindung? Belegcheck-App?

Startbeleg erstellt - OK. Was haben sie womit daran geprüft? Was genau ist "erfolgreich"?
Erster Beleg - was haben sie womit daran geprüft?

Was ist der Status der SE-Einheit und der Kasse in Finanz-Online?

**Comment by j0k3rabg** [comment]
Also ich gehe immer so vor, dass ich zuerst den Beleg/QR Code erstelle, dann wird es durch den Belegcheck-App gescannt und dann je nachdem ob eine Erfolgsmeldung kommt oder nicht schaue ich in FON was dort die Fehlermeldung ist.

Der Status von der SE ist "In Betrieb seit 14.11.2018 14:43". Der Startbeleg wurde erfolgreich akzeptiert und somit ist die RK auch aktiviert geworden

Was ich noch festgestellt habe ist, dass wenn ich einen Folgebeleg erstelle, der 0,00 überall hat, wird der als ein gültiger erkannt. Leider aber sobald mindestens einer von den Beträgen einen anderen Wert hat kommt die oben genannte Fehlermeldung

**Comment by ErichFreitag** [comment]
Tja, dann ist die Frage, woran es liegt (no na) - die Fehlermeldung eines fehlerhaften Signaturwerts hat ja nicht unmittelbar mit Beträgen zu tun.

Ich sehe "aus der Ferne" drei Möglichkeiten:
- sie posten hier die Informationen (Zertifikats-Seriennummer, QR-Codes)

- oder sie stellen die Frage im WKO-RKSV-Forum - da sitzen dahinter FON-Spezialisten, die das auch in der gesamten Kette nachvollziehen und prüfen können

- sie prüfen die maschinenlesbaren Codes mit dem ASIT-Prüftool und schauen, ob sie da mehr Informationen bekommen (meine kurzfristige Empfehlung)

Ansonsten können sie noch prüfen, ob bei der Signaturerstellung irgendetwas verdächtig ist - also beispielsweise die Beträge nicht richtig eingetragen werden, die Beträge nicht richtig in die Signatur einberechnet werden, sich der maschinenlesbare Code mit Nicht-Null-Beträgen auffällig ändert, ...?

**Comment by j0k3rabg** [comment]
Habs herausgefunden, der Umsatszähler war falsch
