### ISSUE TITLE
FinanzOnline Webservice - Ausfall Kasse

### ISSUE THREAD

**Issue by wjjw73** [BMF-RKSV-Technik/at-registrierkassen-mustercode#678]
Hallo!

Wir stellen gerade unser Kassensystem auf FON-Onlineverarbeitung um (statt manueller Konfiguration im FON und Belegübermittlung via App).
Hierzu haben wir alle FinanzOnline Registrierkassen-Webservices implementiert.
Jetzt haben wir begonnen alle **Web-Calls im Testmodus (T) zu Testen**.

Es funktionieren alle bis auf die "**Meldung eines Ausfalls oder einer Außerbetriebnahme einer Registrierkasse**". Hier bekommen wir immer die Fehler-Meldung: "_B9: Nur in Betrieb befindliche Registrierkassen dürfen als ausgefallen gemeldet werden._". Funktioniert das nur ich Echtbetrieb oder übersehe ich da was? 
**Prozess ist**: Login -> Statusabfrage Registrierkasse (OK) -> Ausfallsmeldung -> Logout.

**Zweitens**: Wenn ich den Ausfall als "Ausserbetriebnahme" definiere, kann ich eine solche Kasse wieder in "Wiederinbetriebnahme" setzen?

**Comment by wjjw73** [comment]
Ok, vielleicht heisst ja "In Betrieb befindliche Registrierkasse" das zumindest ein Startbeleg generiert wurde. Das könnte wohlmöglich der Grund sein.
Also nur ein "Registrieren der Kasse" reicht nicht aus um einen Ausfall zu melden. Irgendwie klar.

**Comment by WienerroitherM** [comment]
Hallo!
Genau das ist das Problem. Solange kein gültiger Startbeleg übermittelt wurde steht die Kasse mit dem Status "Registriert" in der Datenbank. Nach Startbelegprüfung dann mit "In Betrieb". Nur "registrierte" Kassen können als ausgefallen gemeldet werden.

Eine Außerbetriebnahme ist endgültig und lässt sich nicht durch eine Wiederinbetriebnahme rückgängig machen.

**Comment by WienerroitherM** [comment]
Hallo!
 Genau das ist das Problem. Solange kein gültiger Startbeleg übermittelt wurde steht die Kasse mit dem Status "Registriert" in der Datenbank. Nach Startbelegprüfung dann mit "In Betrieb". Nur Kassen, die "In Betrieb" sind, können als ausgefallen gemeldet werden.

Eine Außerbetriebnahme ist endgültig und lässt sich nicht durch eine Wiederinbetriebnahme rückgängig machen.

**Comment by wjjw73** [comment]
Super Danke - alles klar.
