### ISSUE TITLE
Detailfragen zum DEP

### ISSUE THREAD

**Issue by grafuzzi** [BMF-RKSV-Technik/at-registrierkassen-mustercode#681]
Guten Abend,

zwei Fragen zum DEP, welche ich aus der Datei "2016-09-05-Detailfragen-RKSV-V1.2.pdf", für mich nicht 100%tig ableiten kann.

1.) Soll bei jedem Ausführen des DEPs ein Startbeleg als erster Eintrag vorhanden sein?
2.) Die kompakte JWS-Signatur wird hinsichtlich der folgenden Zeichen vor der Erstellung des Hash ersetzt
("=", "")
('+', '-')
('/', '_')

Danke,
grafuzzi

**Comment by lebail** [comment]
1.) Einen Startbeleg gibt es nur bei der Inbetriebnahme einer Kasse. Da allerdings das DEP immer vom Beginn an exportiert werden muss, beginnt es immer mit ebendiesem Startbeleg.

2.) Ja, das ist die sogenannte BASE64URL-Kodierung (im Gegensatz zu BASE64). Im Dokument ist immer angegeben, welche Variante zu verwenden ist.

**Comment by grafuzzi** [comment]
Herzlichen Danke an Lebail für die rasche Beantwortung

**Comment by AxelKutschera** [comment]
Wir (fiskaltrust) habe ein eigenes Tool mit dem auch Teile - daher auch ohne Startbeleg - eines DEP7 geprüft werden können.
Die Finanzverwaltung kann dies ebenso.

Abhängig von einem etwaigen Prüfungsauftrag des Finanzamtes kann es sein, dass auch nur ein Teil des DEP7 zur Verfügung zu stellen ist.
