### ISSUE TITLE
DEP7 Division durch 0 oder mathem. Überlauf

### ISSUE THREAD

**Issue by bedengler** [BMF-RKSV-Technik/at-registrierkassen-mustercode#687]
Wir hatten schon mehrere Kassenprüfungen unserer Online-Kasse. Alles bisher einwandfrei. Nun hatte ein Kunde von uns eine Kassenprüfung, bei der beim Einlesen des JSON Files nach 23% beim Einlesevorgang der Fehler kam "Division durch 0 oder mathem. Überlauf".
Ich kann mit dem Fehler nichts anfangen und bin gerade etwas vor den Kopf gestossen und ratlos.
Die Prüfung einzelner Belege (Stichproben) mit Prüftool bzw. App ist in Ordnung.
Bin auch in Kontakt mit dem Finanzamt, um das DEP7 von einem 2. Prüfer nochmals prüfen zu lassen. Da warte ich auf Rückmeldung.
Wir haben bis Donnerstag Zeit, der Prüferin ein DEP7 abzuliefern, das funktioniert. 
Wie gesagt, wir hatten bis jetzt ca. 30 Prüfungen, die alle anstandslos klappten.

Habt ihr Ideen, wie ich an eine Fehlermeldung kommen kann, die mehr Details zum Grund liefert (z.B. welche Zeile/Beleg betroffen ist etc.)?

Wo ist der technische Support des BMF in solchen Fragen? Gibt es überhaupt einen?
Die Hotline beim BMF war ziemlich ratlos...

![Unknown](https://user-images.githubusercontent.com/17435772/65948339-57930600-e43a-11e9-99ef-b0cdae393ab9.jpg)

**Comment by WienerroitherM** [comment]
Hallo!
Der hier erwähnte Einlesevorgang stellt nicht die technische DEP7 Prüfung (Prüf-Tool) dar, sondern erfolgt manuell vom Anwender, nachdem die "technische" .JSON Prüfung abgeschlossen ist und dient der tabellarischen Aufbereitung und inhaltlichen Analyse.
Dieses Problem wird nicht durch ein fehlerhaftes DEP ausgelöst sondern tritt auf, wenn in einem DEP Monate vorhanden sind, in denen nur Belege mit Belegsumme 0,- enthalten sind (zB nur Nullbelege), da bei den in der Prüfersoftware durchgeführten Analysen auch mathemathische Funktionen enthalten sind, die durch die Monatssumme dividieren.
Ich hoffe, ich konnte etwas Klarheit in dieser Angelegenheit schaffen - der Fehler wird im nächsten Release der Analysesoftware behoben werden und sollte dann nicht mehr vorkommen.

Liebe Grüße

**Comment by bedengler** [comment]
Ah ja, ist korrekt. Für die Prüfung wurde heute (1. Oktober, also neues Monat) noch vor Geschäftsbeginn ein Nullbeleg erstellt...somit ist in diesem Monat nur der Nullbeleg vorhanden.
D.h. wenn ich es richtig verstehe läuft die Prüfung durch, sobald eine Rechnung erstellt wurde im Oktober!?

**Comment by WienerroitherM** [comment]
Genau - dann dürfte der Einlese-Fehler nicht mehr auftreten. Unabhängig davon liegt das Problem aber wie gesagt nicht an einem fehlerhaften DEP sondern einem Programmierfehler in der allgemein verwendeten Analysesoftware der Betriebsprüfer, der jedoch umgehend behoben wurde und mit dem Release der nächsten Version nicht mehr auftauchen sollte. 
Auf die technische DEP7 Prüfung der .json Datei (entspricht dem .json Prüf-Tool) hat dieses Problem keine Auswirkung.

**Comment by bedengler** [comment]
Vielen Dank! Dann bin ich beruhigt ;)
Der Vollständigkeit halber hier auch nochmal die Rückmeldung vom Finanzamt:

> Sehr geehrter Herr Dengler,
das Protokoll weist keine Fehler auf und auch die bereits durchgeführte Prüfung mittels „RK-DEP-Übertragung“ war erfolgreich. 
Erst das Einlesen im ACL Mentor (das ist ein Programm für unsere Prüfer) führt zu diesem Fehler „Division durch 0“. Dieser Fehler im internen Programm wird z.B. dann angezeigt, wenn es in einem Monat nur Nullbelege, also keine Belege mit Umsätzen gibt.
Das Protokoll selbst ist nicht fehlerhaft.
Schöne Grüße
[...]"
