### ISSUE TITLE
DEP7 Prüfung: abweichender Systemtyp

### ISSUE THREAD

**Issue by jenshorch** [BMF-RKSV-Technik/at-registrierkassen-mustercode#691]
Wir hatten die Tage eine Prüfung und erhielten ein Protokoll mit einer Reihe von Fehlern die mir bisher niemand erläutern konnte. 
Fehlertyp: inhaltlicher Fehler
Fehlerdetail: abweichender Systemtyp
Text: Belege des verarbeiteten DEP stammen aus einem abweichenden Systemtyp (offen/geschlossen)

Ist dieser Fehler jemanden untergekommen?
Was bedeutet er und wie kann ich ihn beheben?

**Comment by WienerroitherM** [comment]
Der Fehler tritt auf, wenn das Prüftool eine Zertifikatsseriennummer im maschinenlesbaren Code eines Belegs erwartet, darin aber ein Ordnungsbegriff für geschlossene Gesamtsysteme enthalten ist bzw. umgekehrt. Um welche Art von System (offen/geschlossen) es sich beim DEP handelt muss dem Prüftool vom Prüfer manuell mitgeteilt werden, daher kann es auch einfach sein, dass der Prüfer/die Prüferin bei der Bedienung des Prüftools irrtümlich angegeben hat, dass es sich bei der Kasse um ein geschlossenes Gesamtsystem handelt obwohl dies nicht zutrifft oder eben auf diese Angabe vergessen hat, wenn es wirklich ein GGS ist. Würde diesbezüglich nochmal mit dem Prüfer/der Prüferin Kontakt aufnehmen.

**Comment by jenshorch** [comment]
Top-Antwort. Der Prüfer hat sich vertan.
Vielen Dank für den Hinweis.

WienerroitherM <notifications@github.com> schrieb am Mi. 20. Nov. 2019 um
13:48:
