### ISSUE TITLE
Falsche Fehlermeldung beim "Ergebnis der Belegprüfung"

### ISSUE THREAD

**Issue by aunterlu** [BMF-RKSV-Technik/at-registrierkassen-mustercode#692]
In letzter Zeit bekommen wir immer öfter Meldungen von Kunden die bei der Jahresbelegsprüfung folgende Fehlermeldung erhalten:

"Im maschinenlesbaren Code des vorliegenden Belegs ist die Sicherheitseinrichtung als
„ausgefallen“ ausgewiesen. Bitte vergessen Sie nicht, nach der Fehlerbehebung das Ende des
Ausfalls über FinanzOnline zu melden. Sollte dies bereits erfolgt sein, sind keine weiteren
Schritte zur Fehlerbehebung notwendig." 

Dabei wird auch der Inhalt des QR-Codes mitgeschickt aus dem klar ersichtlich ist, dass der Beleg nicht mit ausgefallener Sicherheitseinrichtung erstellt wurde. Wenn der Beleg wirklich mit ausgefallener Sicherheitseinrichtung erstellt worden wäre, dann würde am Ende "U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==" stehen.

Ist schon ärgerlich, dass offensichtliche Fehler auf Seiten des Finanzamts immer beim Kassenhersteller landen und man dann mühsam dem Kunden, Steuerberater oder Finanzprüfer erklären muß wo der Fehler zu suchen ist. 
Technische Ansprechpersonen vom Finanzamt haben wir leider noch immer nicht um diese Fehler zu melden, bzw. auch um Klärungen (vorallem bei nicht so offensichtlichen Fehlern auf Finanzamtsseite) ein wenig leichter  zu machen.

**Comment by AxelKutschera** [comment]
Hallo, 
1. obwohl wir mehrere tausend Kassen betreuen haben wir diese Fehlermeldung bei aktiver Sicherheitseinrichtung noch nicht festgestellt.
2. Das wäre das richtige Forum um eine Antwort vom BMF zu bekommen. 
3. Da uns diese Sonderfälle interessieren, kann ich bei der Fehlersuche bzw. Anfrage ans BMF gerne helfen, Schreiben Sie mich gerne direkt an.
Schönen Abend!

**Comment by aunterlu** [comment]
Hallo Herr Kutschera,

erstmal vielen Dank für das Unterstützungsangebot, sobald ich das Ok vom Kunden habe, kann ich Ihnen die Fehlermeldung weiterschicken. 
Und gut zu wissen, dass hier das richtige Forum für diese Problem ist. 

Laut meinen Mitarbeitern tritt diese spezielle Fehlermeldung erst in den letzten ein/zwei Wochen auf. Der Workaround war den Jänner-Monatsbeleg oder irgendeinen neuen Nullbeleg hinzusenden, das hat dann immer funktioniert. 

Beim Jahresbeleg ist bei unserer Kasse die Sicherheitseinrichtung immer aktiv, anders kann der Beleg nicht erstellt werden. Es kann schon eine falsche Ausfallsmeldung in FinanzOnline vorliegen, aber dann sollte eine andere Fehlermeldung kommen. 

(Unsere Software ist seid 2015 und mittlerweile bei ca. 17.000 Kunden im Einsatz, da haben wir schon einiges an Erfahrung mit Fehlermeldungen.  Alle Beanstandungen waren entweder Fehler bei den Ausfallsmeldungen durch den Kunden (unsere Software macht keine automatischen Meldungen über das Webservice, weil sie offline arbeitet) oder Fehler von den Finanzamtsrechnern aus welchem Grund auch immer. Etwas oder Tage später funktionieren die selben Daten). Die Fehlermeldungen vom Finanzamt sind schon um einiges besser geworden, aber für eine einfache Identifizierung ist da noch viel Verbesserungspotenzial. Am ärgerlichsten sind halt falsche Fehlermeldungen.

Einem Techniker vom Finanzamt dürfte ich die Fehlermeldung weitergeben, falls jemand vom Finanzamt mitliest. 

Schönes Wochenende!

**Comment by aunterlu** [comment]
Herr Wienerroither vom BMF hat sich dieser Sache angenommen und folgendes herausgefunden:

Die Sicherheitseinrichtung war als ausgefallen gemeldet und hatte daher im Teil für die Überprüfung des Status der Sicherheitseinrichtung einen Unterschied zum Beleg festgestellt. Das aufrufende Prüfmodul gibt dann aber diese Fehlermeldung aus. Der erste Satz dieser Fehlermeldung ist in diesem Fall leider falsch. 

Vielen Dank an Herrn Wienerroither für die rasche Aufklärung!
