### ISSUE TITLE
5% MwSt.

### ISSUE THREAD

**Issue by wpichler** [BMF-RKSV-Technik/at-registrierkassen-mustercode#695]
Hallo,

habe gerade das gelesen:
https://www.derstandard.at/story/2000118033686/regierung-will-mehrwertsteuer-fuer-gastronomie-kultur-und-medien-auf-5

Ist dazu schon bekannt wie das RKSV Technisch behandelt werden soll ?

**Comment by gbarsan** [comment]
Eine berechtigte Frage. Binnen ~2 Wochen umsetzen und Kundenkassen updaten wird mehr als bloß spannend...

**Comment by tbc233** [comment]
Mir wurde selbst erst heute klar, wie problematisch das unter Umständen ist. Das BMF das genau diese 5% nun beschließen möchte, hat uns schlicht im Aufbau kein Feld für sowas frei gelassen.
Im Moment wird wohl keine Kassenlösung da draussen das ohne Update (und dann erst mal wissen was genau wie ändern) handlen können.
Ein Punkt, auf den für meinen Geschmack bei der Berichterstattung derzeit viel zu wenig eingegangen wird.

**Comment by AxelKutschera** [comment]
2. Issue dazu: https://github.com/BMF-RKSV-Technik/at-registrierkassen-mustercode/issues/696

**Comment by AxelKutschera** [comment]
Aktuell wird in DE darüber nachgedacht, ob die Kassen gar nicht geändert werden und die "Ermäßigung" nur in der UVA abgezogen werden soll. Das wäre eine akzeptable Lösung, da - zumindest wenn zB alle Warengruppen korrekt sind - gar keine Änderungen in der Kasse gemacht werden müssen.

**Comment by Flanelli** [comment]
Laut Erlass wird jeder Betrag der nicht 10, 13, 19, 20% hat im 0% Feld abgelegt.
Da ist es doch egal ob es weitere Felder für neue Steuersätze gibt oder nicht. 
Alles was nicht vorhanden ist kommt in den Nuller und dazu braucht man doch 
kein Update, außer man hat den Erlass beim Coden nicht richtig verstanden.

**Comment by texTec** [comment]
> Laut Erlass wird jeder Betrag der nicht 10, 13, 19, 20% hat im 0% Feld abgelegt.
> Da ist es doch egal ob es weitere Felder für neue Steuersätze gibt oder nicht.
> Alles was nicht vorhanden ist kommt in den Nuller und dazu braucht man doch
> kein Update, außer man hat den Erlass beim Coden nicht richtig verstanden.

Bitte offizielle Quelle für die "Behauptung" angeben. Auf welchen Erlass beziehen Sie sich da ? Ich bin derselben Meinung wie AlexKutschera, dass der zusätzlich eingeführte Steuersatz 5% in das Feld "Betrag-Satz-Besonders" gehört und nicht in "Betrag-Null"

**Comment by tbc233** [comment]
Da hat er schon nicht unrecht:

https://findok.bmf.gv.at/findok?execution=e1s1 unter 4.6.6.

"Dem Satz 0% sind Bruttobeträge zuzuweisen, die entweder von der USt. befreit sind, beim Unternehmer nicht, nicht zur Gänze bzw. mit einem anderen % als den in Abschnitt 3.3.4. angeführten % der USt. unterliegen oder deren USt. auf Grund anderer Unterlagen geschuldet wird."

Ich gehe aber davon aus dass die wenigsten das auch tatsächlich so implementiert haben damals.

**Comment by texTec** [comment]
> Da hat flanelli schon nicht unrecht:
> 
> https://findok.bmf.gv.at/findok?execution=e1s1 unter 4.6.6.
> 
> "Dem Satz 0% sind Bruttobeträge zuzuweisen, die entweder von der USt. befreit sind, beim Unternehmer nicht, nicht zur Gänze bzw. mit einem anderen % als den in Abschnitt 3.3.4. angeführten % der USt. unterliegen oder deren USt. auf Grund anderer Unterlagen geschuldet wird."
> 
> Ich gehe aber davon aus dass die wenigsten das auch tatsächlich so implementiert haben damals.

Danke. Scheint wirklich so zu sein. Optimal ist es trotzdem nicht.

**Comment by wpichler** [comment]
Dort ist aber auch zu lesen:

> Im Detail handelt es sich dabei zumindest um folgende Geschäftsvorfälle:

Nr. | Geschäftsvorfall
-- | --
1 | Umsatzsteuerbefreite Umsätze, auch unecht befreite Umsätze
2 | Nicht steuerbarer Umsatz
3 | Barzahlung mit Verweis auf Rechnung/Honorarnote (auch Anzahlung, Ratenzahlung, usw.)
4 | Differenzbesteuerte Beträge (teilweise besteuerte Barumsätze)
5 | Mobiler Barumsatz mit Verweis auf händisch erstellten Beleg
6 | Nacherfasste Umsätze nach einem RK-Ausfall (händisch erstellten Beleg)
7 | Kein Barumsatz (zB: Durchlaufender Posten, Wertgutscheine, Auslandumsätze, Privatentnahmen, Schwund, usw.)

Eine Klarstellung des BMF dazu wäre hier sehr hilfreich...

**Comment by Flanelli** [comment]
Wieso führen Sie ein <**ABER auch**> an?
Die angeführten Gesch#ftsvorfälle 1 bis 7 haben mit dem Thema <weitere Steuersätze>,
im konkreten Fall der 5%tige nichts zu tun und sind klar verständlich dargestellt.

Vor dem Satz **Im Detail handelt es sich dabei zumindest um folgende Geschäftsvorfälle:**
steht doch klar und unmissverständlich 

**Dem Satz 0% sind Bruttobeträge zuzuweisen**, die entweder von der USt. befreit sind, beim 
Unternehmer nicht, nicht zur Gänze **_bzw. mit einem anderen % als den in Abschnitt 3.3.4. 
angeführten % der USt. unterliegen_** oder deren USt. auf Grund anderer Unterlagen 
geschuldet wird.  

Was nun das BMF diesbezüglich noch klarstellen sollte, erschließt sich mir nun wirklich nicht.
Ein Zusatzerklärung, dass der 5%-tige Steuersatz nicht in der Auflistung 10, 13, 19, 20 vorhanden
ist und daher diese Regelung nun eintritt, ist doch völlig überflüssig.

**Comment by tbc233** [comment]
Ich seh das auch so dass es, sofern nicht etwas anderes verordnet wird, tatsächlich derzeit so ist dass das 0er Feld schon immer als Auffangbecken für "eh alles sonst gedacht" war.

Die Situation ist aber dass beinahe jeder (mich eingeschlossen) mit dem ich mich so austausche dies derzeit nicht so implementiert hat. Da nun bald wieder eine Woche rum ist ohne dass man weiß ob die 5% Geschichte überhaupt kommen wird, kann es mal sicherlich nicht schaden wenn jene die das bisher nicht so implementiert haben, das mal so umsetzen. Da es sowieso schon immer gegolten hätte, ist da mal sicher nichts veloren, ist zumindest meine Sicht.

**Comment by wpichler** [comment]
Wir haben es so implementiert das wir die Steuersätze den entsprechenden Steuerklassen zuordnen können, also kein Problem von der Seite her...

Den Gesetzestext interpretiere ich eindeutig anders - es steht da ja allgemein gehalten für welche Fälle der 0% Satz gehört, und dann wird das noch im Detail ausgeführt. Und im Detail ist dann dieser 5% Fall nicht aufgelistet.

Aber das ist vielleicht zu viel Techniker Denkweise - und man benötigt hier eher Juristen Denkweise.

Mir soll es Recht sein - eine Bestätigung wäre trotzdem doch sicher kein Problem von der SEite BMF, oder ist das zu viel verlangt ?

**Comment by wpichler** [comment]
Stimmt - das zumindest relativiert das ganze wieder. Klarer Punkt für @MichaelSchustereder und @Flanelli 
Also den 0% Satz verwenden falls nicht noch was anderes kommen sollte in der Zwischenzeit

**Comment by Flanelli** [comment]
Ich bin jedenfalls ein glühender Verfechter für klare, unmissverständliche Beschreibungen, insbesondere wenn diese in Tintenburgen konzipiert und erstellt werden aber hier ist absolut alles völlig unmißverständlich und auch frei von jeglicher Interpretationsmöglichkeit beschrieben worden.
Auch Techniker sind eigentlich des sinnerfassenden Lesens kundig und nicht mehr als diese Anforderung wird hier gestellt.

Vor dem Satz Im Detail handelt es sich dabei zumindest um folgende Geschäftsvorfälle:
steht doch klar und unmissverständlich

Dem Satz 0% sind Bruttobeträge zuzuweisen, die entweder von der USt. befreit sind, beim
Unternehmer nicht, nicht zur Gänze bzw. mit einem anderen % als den in Abschnitt 3.3.4.
angeführten % der USt. unterliegen oder deren USt. auf Grund anderer Unterlagen
geschuldet wird. Im Detail handelt es sich dabei zumindest um folgende Geschäftsvorfälle:

Daher nochmals, es gibt nicht den geringsten Grund für eine Änderung des Erlasses um nun
dezidiert die Handhabung der 5%tigen Bruttobeträge zu erklären und festzuhalten. 
Es wurde bereits für solche Fälle alles bereits festgehalten und kommuniziert.

Wenn man dem Wortlaut des Erlasses nicht traut sthet es doch jedem frei, beim BMF eine 
Anfrage mit Ersuchen um eine nochmalige, und mit dem Zusatz des 5%-Falles eine dezidierte Bestätigung der bereits beschriebenen Handhabung zu stellen. 

Ja, es gibt so manchen Erlass, der höchst dubios gestaltet ist und auch tatsächlich enorm viel Spielraum für Interpretationen zuläßt ( siehe Corona ). aber als ebenfalls Techniker mit Leib und Seele
halte mich gerne an klar formulierte Angaben die tunlichst keinen Spielraum für Interpretationen zulassen und genau das ist hier definitiv der Fall.

Amen....

**Comment by wpichler** [comment]
Hier noch ein Link dazu...
https://www.bmf.gv.at/public/informationen/informationen-coronavirus/registrierkassen.html
