### ISSUE TITLE
Fehler beim Versuch die Signatureinheit über WebService zu registrieren

### ISSUE THREAD

**Issue by AlgoLinz** [BMF-RKSV-Technik/at-registrierkassen-mustercode#697]
Hallo,

kennt jemand vielleicht das folgende Problem?

Habe heute versucht eine Registrierkasse beim Kunden zu aktivieren und beim Registrieren der Signatureinheit (über WebService) bekam ich folgende automatische Antwort von Finanzamt:

Fehler beim Erstellen der HTTP-Anforderung für https://finanzonline.bmf.gv.at/fonws/ws/sessionService. Dies ist möglicherweise darauf zurückzuführen, dass das Serverzertifikat im Fall von HTTPS nicht ordnungsgemäß mit HTTP.SYS konfiguriert wurde. Eine andere mögliche Ursache kann eine fehlende Übereinstimmung bei der Sicherheitsbindung zwischen Client und Server sein.

Alle bis heute in Betrieb genommenen Registrierkassen wurden problemlos registriert und aktiviert.

Danke für alle Hinweise

**Comment by Phoniexk** [comment]
Falls die Frage noch offen ist:

Es kann hier mehrere Gründe geben. Kommt auf das Kunden-OS und auch auf die Software-Architektur darauf an.
Bei FON gab es vor 1-2 Monaten eine Umstellung der TLS-Konfiguration.

Ein möglicher Grund wäre, dass das Client-System (z.B. PC vom Kunden) keine entsprechende Chiper untersützt - zumindest unter Windows kann das ein Grund sein. Wenn es sich um ein Windows-System handelt, dann einfach über den IE versuchen die Seite https://finanzonline.bmf.gv.at/fon/ (oder den Link von Ihnen) zu öffnen. Geht das nicht, dann sind vermutlich am System bestimmte Chiper deaktiviert.

Andernfalls Traffic-Sniffer verwenden und den Aufbau der TLS-Verbindung untersuchen, dort sollte sich dann der Grund finden lassen. Mittels https://www.ssllabs.com/ kann man sich die verfügbaren Chiper ansehen.

**Comment by AlgoLinz** [comment]
Danke
