### ISSUE TITLE
Prüftool meldet Der Umsatzzähler konnte nicht entschlüsselt werden

### ISSUE THREAD

**Issue by rierup** [BMF-RKSV-Technik/at-registrierkassen-mustercode#700]
Wenn ich nur den Startbeleg erstelle und das DEP exportiere und
dieses dann mit dem Prüftool teste, 
erhalte ich beim Startbeleg 'Der Umsatzzähler konnte nicht entschlüsselt werden'
Wenn ich dann noch zusätzlich Normalbelege erfasse und wieder 
exportiere und prüfe, dann sind alle Normalbelege OK nur der Startbeleg nicht.
Obwohl die Umsatzzählerverschlüsselung bei allen Sätzen die gleiche Funktion ist und
der Umsatzzähler beim Startbeleg sicher 0 ist.
Hab ich da beim Startbeleg noch etwas übersehen?

AESKey: 1juBWVrdrTlmUwPGMv85ZZENyYdpqu0SHht6DzhXW3LU

[DEP-full.json.log](https://github.com/BMF-RKSV-Technik/at-registrierkassen-mustercode/files/5359210/DEP-full.json.log)
[DEP1.json.log](https://github.com/BMF-RKSV-Technik/at-registrierkassen-mustercode/files/5359211/DEP1.json.log)
[cryptographicMaterialContainer.json.log](https://github.com/BMF-RKSV-Technik/at-registrierkassen-mustercode/files/5359213/cryptographicMaterialContainer.json.log)

**Comment by Flanelli** [comment]
Haben Sie beim Startbeleg berücksichtigt, dass Verkettungswert  zum vorigen Beleg 
über  die  Kassen-ID gebildet wird, da es ja keine vorigen Beleg gibt?

**Comment by rierup** [comment]
Danke für die Nachricht.
Es funktioniert aber inzwischen, ich hab mich nur mit dem Schlüssel vertan.
