### ISSUE TITLE
Kann die ID nicht finden

### ISSUE THREAD

**Issue by aleks300** [BMF-RKSV-Technik/at-registrierkassen-mustercode#704]
Hallo, 

ich versuche gerade ein passendes cryptographicMaterialContainer.json file zu erstellen.
Ich habe den AES Key, das Certificate und das einzige was mir fehlt ist die ID.
ich bin besitz einer RKS-Card von Globaltrust, und habe anfangs gedacht die Karten-Serien-Nummer ist die ID, jedoch war dem nicht so, ich bekam eine Fehlermeldung. Anschließend probierte ich die Zertifikat Seriennummer und bekam auch wieder die selbe Fehlermeldung wie vorher, die da wäre: 
"_Die Prüfung des Belegs konnte nicht vollständig durchgeführt werden. Vermutlich konnte das Zertifikat oder der Schlüssel mit der im Beleg angegeben Seriennummer bzw. dem angegebenen Ordnungsbegriff des Unternehmens und der Schlüssel-ID nicht in der cryptographicMaterialContainer.json Datei gefunden werden. Bitte überprüfen Sie diese Datei und die darin hinterlegten Informationen. Diese Fehlermeldung ist nur im Prüftool relevant und wird in dieser Form nicht bei der Echtprüfung über FinazOnline vorkommen_."

Jetzt sind mir die Ideen ausgegangen was denn noch die ID sein könnte und hoffe das mir da jemand weiter helfen kann.
Vielleicht hat jemand Erfahrung mit Globaltrust und weiß von wo man sich die ID holen kann.

Vielen Dank, 

Aleks

**Comment by WienerroitherM** [comment]
Hallo!
In die cryptographicMaterialContainer.json muss die Zertifikatsseriennummer rein, das stimmt schon so.
Im Rahmen des Prüftools ist diese allerdings casesensitive und Groß-/Kleinschreibung muss daher im Beleg und cryptographicMaterialContainer.json ident sein. Ist dies nicht der Fall wird kommt auch die oben angeführte Fehlermeldung.
Ich vermute, dass der Fehler daran liegt.

LG
Michael

**Comment by aleks300** [comment]
Danke.
