### ISSUE TITLE
Prüftool für Single Receipt

### ISSUE THREAD

**Issue by ralpheichelberger** [BMF-RKSV-Technik/at-registrierkassen-mustercode#709]
Laut Ihrer Dokumentation "Detailfragen-RKSV" soll man hiermit die Korrektheit einer einzelnen maschinenlesbaren Representation prüfen können:

java -jar regkassen-verification-receipts-1.1.1.jar -v -f -i repfile -c CryptographicMaterialContainer.json -o OUTPUT_DIR
Parsing cryptographic material container from /home/ralph/workspace/go_rksv/testtool/CryptographicMaterialContainer.json
Error while parsing the input files.

Die Files habe ich mit den Daten aus dem Dokument gefüllt:

```
CryptographicMaterialContainer.json 
{
  "base64AESKey": "BwZ8o6bv2XoABMSeLDvr5VrhNpwWLDklS1plk3TeBqU=",
  "certificateOrPublicKeyMap": {
    "816d29a919370f0c": {
      "id": "816d29a919370f0c",
      "signatureDeviceType": "CERTIFICATE",
      "signatureCertificateOrPublicKey":"MIIBSTCB8KADAgECAgh+ktZW5sjw9DAKBggqhkjOPQQDAjAWMRQwEgYDVQQDDAtSZWdLYXNzYSBDQTAeFw0xNjAzMDUxOTQ1MDJaFw0xNjAzMDYxOTQ1MTJaMB4xHDAaBgNVBAMME1NpZ25pbmcgY2VydGlmaWNhdGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQg/H2XYKNKhowvHESHADoKvw2V63+A2acOUPmdbR51Vbca4lvHEr1S1843WNuxILXXZURn0740m0JmGeg2H5+goyAwHjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAKBggqhkjOPQQDAgNIADBFAiAYj25MfdCWtyxSt3/ggkFvdJ/WIbiq0Oe99gwfbOnwaAIhANApaLXif7PDXvL4ombusXwEVtZg3ABVTqviyb9Uu31T"
    }
  }
}

repfile 
_R1-AT0_DEMO-CASH-BOX524_366596_2015-12-17T11:23:44_0,00_0,00_3,64_-2,60_1,79_VFJB_47be737cb1f6d1f1_ZvNxJw6a1A4=_J7YC28zquHfHzMpx02TqElbXOTSgXQu5JAA9Xu1Xzzu5p8eUYT+sgmyhzRps5nYyEp5Yh8ATIa9130zmuiACHw==

```
Was soll ich mit einem Fehler "Error while parsing the input files." anfangen? Nochdazu wenn diese Daten aus dem Dokument eigentlich korrekt sein sollten, oder?

Dazu ist es nicht möglich den Vorgang zu debuggen, da die meisten relevanten Sources nicht zur Verfügung stehen und das Projekt in dieser fragmentieren Art nicht lauffähig ist. 
Für die Prüftools gibt es nur die JAR-Files ohne Source, für die Kasse nur die Sourcefiles, die nach einem erfolgreichem Maven Build trotzdem nicht läuft.

Wie kann ich nun prüfen ob meine Implementierung korrekt ist?

**Comment by WienerroitherM** [comment]
Hallo!

Der Beleg im repfile muss in []-Klammern und Anführungszeichen gesetzt werden, dann sollte die Prüfung laufen:
["_R1-AT0_DEMO-CASH-BOX524_366596_2015-12-17T11:23:44_0,00_0,00_3,64_-2,60_1,79_VFJB_47be737cb1f6d1f1_ZvNxJw6a1A4=_J7YC28zquHfHzMpx02TqElbXOTSgXQu5JAA9Xu1Xzzu5p8eUYT+sgmyhzRps5nYyEp5Yh8ATIa9130zmuiACHw=="]

Im Beleg selbst wird aber mit "_R1-AT0" angegeben, dass ein geschlossenes Gesamtsystem verwendet wird. Das passt in weiterer Folge nicht zur angegebenen Zertifikatsseriennummer (bei GGS muss anstelle dieser der Ordnungsbegriff stehen) und wird bei der Prüfung einen Fehler retournieren.

Das Crypto-file ist vom Aufbau her korrekt, allerdings ist darin ein anderes Zertifikat eingetragen, als dann im Beleg angegeben wird (816d29a919370f0c vs. 47be737cb1f6d1f1).

LG

**Comment by ralpheichelberger** [comment]
Vielen Dank für dir prompte Rückmeldung. 

Das Format mit den eckigen Klammern habe ich in der Doku nirgends entdecken können. Die Prüfung des Start-Belegs konnte ich inzwischen mit dem regkassen-verification-receipts-1.1.1.jar erfolgreich durchführen. 

Auch das DEP Format scheint der Prüfung standzuhalten nur wird mir die Verkettung der Belege als ungültig attestiert:

> "Die Verkettung zwischen dem vorigen Beleg und dem aktuellen Beleg ist ungültig. Bitte überprüfen Sie die Berechnung des Verkettungswerts oder die Abfolge der maschinenlesbaren Codes im exportierten RKSV-DEP."

Dabei werden die ersten 8 Byte des SHA256 HASH-Wert des signierten JWT BASE64 codiert als 12. Element an die Representation angehängt. Ich kann nicht nachvollziehen was ich dabei falsch machen kann.

`
base64.StdEncoding.EncodeToString(sha256.Sum256([]byte(prevJWT))[:][:8])
`

Was genau ist hier ungültig?

**Comment by ralpheichelberger** [comment]
War nur das Format mit den [" "], welches ich nirgends beschrieben gefunden habe.

**Comment by ralpheichelberger** [comment]
War nur das Format mit den [" "], welches ich nirgends beschrieben gefunden habe.
