### ISSUE TITLE
Bezahlarten

### ISSUE THREAD

**Issue by ckvsoft** [BMF-RKSV-Technik/at-registrierkassen-mustercode#721]
Vielleicht eine Dumme Offtopic Frage, nur kann ich darüber nichts finden.
Auf diversen Belegbeispielen steht es immer drauf und in den texten steht eben nicht das es Pflicht ist.

Muss die Bezahlart (BAR, BANKOMAT, KREDITKARTE)  am Kassabon stehen oder nicht?

**Comment by AxelKutschera** [comment]
> Muss die Bezahlart (BAR, BANKOMAT, KREDITKARTE) am Kassabon stehen oder nicht?

Gesetzlich ist es kein Belegmerkmal.

Hier habe ich eine Übersicht der Belegmerkmale nach UStG, BAO und RKSV: https://www.fiskaltrust.at/wp-content/uploads/2017/07/170703_ft-Belegmerkmale.pdf

**Comment by ckvsoft** [comment]
Danke, Alles klar
LG Chris

**Comment by aunterlu** [comment]
Auch wenn es kein Belegmerkmal ist, in der Kasse selbst muß es meiner Meinung nach aufgrund der Kassenrichtlinie 2012 erfasst werden: https://findok.bmf.gv.at/findok?execution=e100000s1&segmentId=c6caaf1e-a563-4172-b52c-3ff9f9c12983

**Comment by ckvsoft** [comment]
Dann bin ich wieder soweit wie Vorher ;-)
Dann ist es wieder irgenwie Unklar. Es war eine Kundenanfrage ob man das nicht weg lassen kann.

**Comment by AxelKutschera** [comment]
Wenn der Zahlweg (elektronisch) erfasst wird, muss die Information aufbewahrt werden.

Es ist jedoch kein notwendiges Belegmerkmal.

Die Meinung des BMF aus der krl2012 ändert daran nichts.
